server {
    listen 80 default_server;
    server_name crm-realstate.com www.crm-realstate.com 192.168.1.10;  # Added your IP address

    location / {
        proxy_pass http://206.81.28.127:3000;  # Frontend Vite preview server
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /api {
        proxy_pass http://206.81.28.127:5432;  # Backend server
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
